# GitHub Actionsワークフロー: GitHub Pagesへの自動デプロイ

name: Deploy to GitHub Pages

on:
  # mainブランチにpushされたときにワークフローを実行
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. peaceiris/actions-gh-pages を使用してデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # 公開するディレクトリ (リポジトリのルート)